In [2]:
import pandas as pd
import numpy as np  
import scipy as sp

In [3]:
a = [10, 3, 5, 12, 50]
b = [5, 4, 3, 2, 1]
array_a = np.array(a)
array_b = np.array(b)

In [4]:
print(a)
print(b)
print(array_a)
print(array_b)

print("multiplication:", array_a * array_b)
print("addition:", array_a + array_b)
print("subtraction:", array_a - array_b)
print("division:", array_a / array_b)

[10, 3, 5, 12, 50]
[5, 4, 3, 2, 1]
[10  3  5 12 50]
[5 4 3 2 1]
multiplication: [50 12 15 24 50]
addition: [15  7  8 14 51]
subtraction: [ 5 -1  2 10 49]
division: [ 2.          0.75        1.66666667  6.         50.        ]


In [15]:
height = [178, 165, 180, 172, 185, 169, 174]

In [ ]:
print(np.mean(height))
print(np.std(height)) # standard deviation
print(np.max(height))
print(np.min(height))


174.71428571428572
6.318098396427423
185
165


In [ ]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

aa = np.array(a)
bb = np.array(b)

mc = np.dot(matrix_a, matrix_b) # matrix multiplication
print(mc)

[[19 22]
 [43 50]]


In [ ]:
data = {
    "name" : ["John Doe", "Jane Smith", "Emily Davis"],
    "age" : [22, 24, 21],
    "degree" : ["Information Systems", "Computer Science", "Data Science"]
}


print(pd.DataFrame.from_dict(data, orient="index"))

                          0                 1             2
name               John Doe        Jane Smith   Emily Davis
age                      22                24            21
degree  Information Systems  Computer Science  Data Science


In [6]:
datas = pd.read_csv("calon_tni.csv")

print(datas)
print()
statistics = datas["tinggi"].describe()
print("Statistika deskriptif\n",statistics)

print()

print("mean:", np.mean(datas["tinggi"]))
print("std:", np.std(datas["tinggi"]))
print("max:", np.max(datas["tinggi"]))
print("min:", np.min(datas["tinggi"]))
print("median", np.median(datas["tinggi"]))


    nama                    alamat  tinggi
0   Andi        Jl. Merdeka No. 10     175
1   Budi        Jl. Sudirman No. 5     178
2  Citra        Jl. Thamrin No. 20     180
3   Dewi  Jl. Gatot Subroto No. 15     180
4    Eka     Jl. Rasuna Said No. 8     183
5  Fajar       Jl. Kuningan No. 12     185
6   Gina          Jl. Cikini No. 3     170
7   Hadi        Jl. Palmerah No. 7     168
8  Indah         Jl. Senayan No. 9     178
9  Jilan        Jl. Kuningan No. 2     160

Statistika deskriptif
 count     10.000000
mean     175.700000
std        7.645623
min      160.000000
25%      171.250000
50%      178.000000
75%      180.000000
max      185.000000
Name: tinggi, dtype: float64

mean: 175.7
std: 7.2532751223154355
max: 185
min: 160
median 178.0
